/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuchEinzelansichtPanel.java
 *
 * Created on 20.03.2009, 14:10:17
 */

package bibliotheksverwaltung.view;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

import bibliotheksverwaltung.controller.ExemplarHinzuListener;
import bibliotheksverwaltung.model.domain.Medium;
import bibliotheksverwaltung.model.logic.ExemplarVerwalter;
import bibliotheksverwaltung.model.logic.MedienVerwalter;

/**
 *
 * @author Max
 */
public class BuchEinzelansichtPanel extends javax.swing.JPanel implements Observer {

	private MedienVerwalter medienVerwalter = null;
	private Medium medium = null;
	
	//TODO Scrollpane unter dem exemplarpanel, da sonst nur begrenzte anzahl an exemplaren geben kann

	/** Creates new form BuchEinzelansichtPanel */
	public BuchEinzelansichtPanel(MedienVerwalter derVerwalter) {
		initComponents();
		this.medienVerwalter = derVerwalter;
		this.medium = medienVerwalter.getMedium();
		this.buchansichtPanel.add(new BuchAnsicht(this.medium));
		this.erzeugeExemplarAnsichten();
		this.addButton.addActionListener(new ExemplarHinzuListener(medienVerwalter));
	}
	
	private void erzeugeExemplarAnsichten()
	{
		for (int i = 0; i < this.medium.getExemplare().size(); i++)
		{			
			//TODO GridBagLayout entfernen, von Hand gesetzt, da sonst keine Exemplaransichten...
			exemplarePanel.setLayout(new GridLayout(i+1,1));
			AusleiheEinzelansichtPanel panel = new AusleiheEinzelansichtPanel(medienVerwalter, this.medium.getExemplare().get(i));
			exemplarePanel.add(panel);
		}
		this.validate();
		this.repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buchansichtPanel = new javax.swing.JPanel();
		aktionenPanel = new javax.swing.JPanel();
		addButton = new javax.swing.JButton();
		editButton = new javax.swing.JButton();
		historyButton = new javax.swing.JButton();
		printButton = new javax.swing.JButton();
		exemplarePanel = new javax.swing.JPanel();

		setPreferredSize(new java.awt.Dimension(597, 600));

		buchansichtPanel.setOpaque(false);

		javax.swing.GroupLayout buchansichtPanelLayout = new javax.swing.GroupLayout(buchansichtPanel);
		buchansichtPanel.setLayout(buchansichtPanelLayout);
		buchansichtPanelLayout.setHorizontalGroup(
				buchansichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 298, Short.MAX_VALUE)
		);
		buchansichtPanelLayout.setVerticalGroup(
				buchansichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 331, Short.MAX_VALUE)
		);

		aktionenPanel.setOpaque(false);

		addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/add_48.png"))); // NOI18N
		addButton.setText("Exemplar hinzufügen");
		addButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
		addButton.setIconTextGap(10);

		editButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/pencil_48.png"))); // NOI18N
		editButton.setText("Daten bearbeiten");
		editButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
		editButton.setIconTextGap(10);

		historyButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		historyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/clock_48.png"))); // NOI18N
		historyButton.setText("Historie anzeigen");
		historyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
		historyButton.setIconTextGap(10);

		printButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/printer_48.png"))); // NOI18N
		printButton.setText("Daten drucken");
		printButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
		printButton.setIconTextGap(10);

		javax.swing.GroupLayout aktionenPanelLayout = new javax.swing.GroupLayout(aktionenPanel);
		aktionenPanel.setLayout(aktionenPanelLayout);
		aktionenPanelLayout.setHorizontalGroup(
				aktionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aktionenPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(aktionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(editButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
								.addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
								.addComponent(historyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
								.addComponent(printButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
								.addContainerGap())
		);
		aktionenPanelLayout.setVerticalGroup(
				aktionenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(aktionenPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(addButton)
						.addGap(69, 69, 69)
						.addComponent(editButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(historyButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(printButton)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		exemplarePanel.setOpaque(false);

		javax.swing.GroupLayout exemplarePanelLayout = new javax.swing.GroupLayout(exemplarePanel);
		exemplarePanel.setLayout(exemplarePanelLayout);
		exemplarePanelLayout.setHorizontalGroup(
				exemplarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 587, Short.MAX_VALUE)
		);
		exemplarePanelLayout.setVerticalGroup(
				exemplarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 263, Short.MAX_VALUE)
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(buchansichtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(aktionenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(exemplarePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(buchansichtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(aktionenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(exemplarePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
	}// </editor-fold>//GEN-END:initComponents

	public static void main(String args[]) {
		JFrame jframe = new JFrame();
		jframe.setSize(200,265);
		Medium einMedium = new Medium(5);
		einMedium.erzeugeExemplare();
		jframe.add(new BuchEinzelansichtPanel(new MedienVerwalter(einMedium)));
		jframe.setVisible(true);
		jframe.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JPanel aktionenPanel;
	private javax.swing.JPanel buchansichtPanel;
	private javax.swing.JButton editButton;
	private javax.swing.JPanel exemplarePanel;
	private javax.swing.JButton historyButton;
	private javax.swing.JButton printButton;
	// End of variables declaration//GEN-END:variables
	/* (non-Javadoc)
	 * @see java.util.Observer#update(java.util.Observable, java.lang.Object)
	 */
	@Override
	public void update(Observable o, Object arg)
	{
		// TODO Auto-generated method stub

	}

}
