/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HinzufuegenPanel.java
 *
 * Created on 24.03.2009, 14:40:10
 */

package bibliotheksverwaltung.view;

import javax.swing.JTextField;

/**
 *
 * @author Max
 */
public class HinzufuegenPanel extends javax.swing.JPanel {

    /** Creates new form HinzufuegenPanel */
    public HinzufuegenPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSeparator = new javax.swing.JSeparator();
        buchPanel = new javax.swing.JPanel();
        vornameField1 = new javax.swing.JTextField();
        nachnameField1 = new javax.swing.JTextField();
        strasseField1 = new javax.swing.JTextField();
        hausnummerField1 = new javax.swing.JTextField();
        plzField1 = new javax.swing.JTextField();
        stadtField1 = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        personenPanel = new javax.swing.JPanel();
        vornameField = new javax.swing.JTextField();
        nachnameField = new javax.swing.JTextField();
        strasseField = new javax.swing.JTextField();
        hausnummerField = new javax.swing.JTextField();
        plzField = new javax.swing.JTextField();
        stadtField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(593, 600));

        vornameField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        vornameField1.setForeground(new java.awt.Color(204, 204, 204));
        vornameField1.setText("Vorname");
        vornameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vornameField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vornameField1FocusLost(evt);
            }
        });

        nachnameField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nachnameField1.setForeground(new java.awt.Color(204, 204, 204));
        nachnameField1.setText("Nachname");
        nachnameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nachnameField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nachnameField1FocusLost(evt);
            }
        });

        strasseField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        strasseField1.setForeground(new java.awt.Color(204, 204, 204));
        strasseField1.setText("Straße");
        strasseField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                strasseField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                strasseField1FocusLost(evt);
            }
        });

        hausnummerField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hausnummerField1.setForeground(new java.awt.Color(204, 204, 204));
        hausnummerField1.setText("Nummer");
        hausnummerField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hausnummerField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hausnummerField1FocusLost(evt);
            }
        });

        plzField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        plzField1.setForeground(new java.awt.Color(204, 204, 204));
        plzField1.setText("PLZ");
        plzField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plzField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plzField1FocusLost(evt);
            }
        });

        stadtField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        stadtField1.setForeground(new java.awt.Color(204, 204, 204));
        stadtField1.setText("Stadt");
        stadtField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stadtField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stadtField1FocusLost(evt);
            }
        });

        addButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/user_add_48.png"))); // NOI18N
        addButton1.setText("<html>Person<br />hinzufügen");
        addButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addButton1.setIconTextGap(10);

        javax.swing.GroupLayout buchPanelLayout = new javax.swing.GroupLayout(buchPanel);
        buchPanel.setLayout(buchPanelLayout);
        buchPanelLayout.setHorizontalGroup(
            buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buchPanelLayout.createSequentialGroup()
                .addGroup(buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buchPanelLayout.createSequentialGroup()
                        .addComponent(vornameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nachnameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(buchPanelLayout.createSequentialGroup()
                        .addComponent(plzField1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stadtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buchPanelLayout.createSequentialGroup()
                        .addComponent(strasseField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hausnummerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(addButton1))
        );
        buchPanelLayout.setVerticalGroup(
            buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buchPanelLayout.createSequentialGroup()
                .addGroup(buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vornameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nachnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strasseField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hausnummerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plzField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stadtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        vornameField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        vornameField.setForeground(new java.awt.Color(204, 204, 204));
        vornameField.setText("Vorname");
        vornameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vornameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vornameFieldFocusLost(evt);
            }
        });

        nachnameField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nachnameField.setForeground(new java.awt.Color(204, 204, 204));
        nachnameField.setText("Nachname");
        nachnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nachnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nachnameFieldFocusLost(evt);
            }
        });

        strasseField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        strasseField.setForeground(new java.awt.Color(204, 204, 204));
        strasseField.setText("Straße");
        strasseField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                strasseFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                strasseFieldFocusLost(evt);
            }
        });

        hausnummerField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hausnummerField.setForeground(new java.awt.Color(204, 204, 204));
        hausnummerField.setText("Nummer");
        hausnummerField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hausnummerFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hausnummerFieldFocusLost(evt);
            }
        });

        plzField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        plzField.setForeground(new java.awt.Color(204, 204, 204));
        plzField.setText("PLZ");
        plzField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plzFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plzFieldFocusLost(evt);
            }
        });

        stadtField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        stadtField.setForeground(new java.awt.Color(204, 204, 204));
        stadtField.setText("Stadt");
        stadtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stadtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stadtFieldFocusLost(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/user_add_48.png"))); // NOI18N
        addButton.setText("<html>Person<br />hinzufügen");
        addButton.setActionCommand("<html>Person<br />hinzufügen");
        addButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addButton.setIconTextGap(10);

        javax.swing.GroupLayout personenPanelLayout = new javax.swing.GroupLayout(personenPanel);
        personenPanel.setLayout(personenPanelLayout);
        personenPanelLayout.setHorizontalGroup(
            personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personenPanelLayout.createSequentialGroup()
                .addGroup(personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personenPanelLayout.createSequentialGroup()
                        .addComponent(vornameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nachnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(personenPanelLayout.createSequentialGroup()
                        .addComponent(plzField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stadtField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personenPanelLayout.createSequentialGroup()
                        .addComponent(strasseField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hausnummerField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap())
        );
        personenPanelLayout.setVerticalGroup(
            personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personenPanelLayout.createSequentialGroup()
                .addGroup(personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personenPanelLayout.createSequentialGroup()
                        .addGroup(personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vornameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nachnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strasseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hausnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plzField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stadtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(543, 543, 543))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                        .addGap(496, 496, 496))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(515, 515, 515))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vornameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vornameFieldFocusGained
        focusGained(vornameField, "Vorname");
}//GEN-LAST:event_vornameFieldFocusGained

    private void vornameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vornameFieldFocusLost
        focusLost(vornameField, "Vorname");
}//GEN-LAST:event_vornameFieldFocusLost

    private void strasseFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strasseFieldFocusGained
        focusGained(strasseField, "Straße");
}//GEN-LAST:event_strasseFieldFocusGained

    private void strasseFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strasseFieldFocusLost
        focusLost(strasseField, "Straße");
}//GEN-LAST:event_strasseFieldFocusLost

    private void nachnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nachnameFieldFocusGained
        focusGained(nachnameField, "Nachname");
}//GEN-LAST:event_nachnameFieldFocusGained

    private void nachnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nachnameFieldFocusLost
        focusLost(nachnameField, "Nachname");
}//GEN-LAST:event_nachnameFieldFocusLost

    private void hausnummerFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hausnummerFieldFocusGained
        focusGained(hausnummerField, "Nummer");
}//GEN-LAST:event_hausnummerFieldFocusGained

    private void hausnummerFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hausnummerFieldFocusLost
        focusLost(hausnummerField, "Nummer");
}//GEN-LAST:event_hausnummerFieldFocusLost

    private void plzFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plzFieldFocusGained
        focusGained(plzField, "PLZ");
}//GEN-LAST:event_plzFieldFocusGained

    private void plzFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plzFieldFocusLost
        focusLost(plzField, "PLZ");
}//GEN-LAST:event_plzFieldFocusLost

    private void stadtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stadtFieldFocusGained
        focusGained(stadtField, "Stadt");
}//GEN-LAST:event_stadtFieldFocusGained

    private void stadtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stadtFieldFocusLost
        focusLost(stadtField, "Stadt");
}//GEN-LAST:event_stadtFieldFocusLost

    private void vornameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vornameField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_vornameField1FocusGained

    private void vornameField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vornameField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_vornameField1FocusLost

    private void nachnameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nachnameField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nachnameField1FocusGained

    private void nachnameField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nachnameField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nachnameField1FocusLost

    private void strasseField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strasseField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_strasseField1FocusGained

    private void strasseField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strasseField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_strasseField1FocusLost

    private void hausnummerField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hausnummerField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hausnummerField1FocusGained

    private void hausnummerField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hausnummerField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hausnummerField1FocusLost

    private void plzField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plzField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_plzField1FocusGained

    private void plzField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plzField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_plzField1FocusLost

    private void stadtField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stadtField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stadtField1FocusGained

    private void stadtField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stadtField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_stadtField1FocusLost

    private void focusGained(JTextField field, String match) {
        if (field.getText().equals(match)) {
            field.setText("");
            field.setForeground(new java.awt.Color(0, 0, 0));
        }
    }

    private void focusLost(JTextField field, String content) {
        if (field.getText().isEmpty()) {
            field.setForeground(new java.awt.Color(204, 204, 204));
            field.setText(content);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JPanel buchPanel;
    private javax.swing.JTextField hausnummerField;
    private javax.swing.JTextField hausnummerField1;
    private javax.swing.JSeparator menuSeparator;
    private javax.swing.JTextField nachnameField;
    private javax.swing.JTextField nachnameField1;
    private javax.swing.JPanel personenPanel;
    private javax.swing.JTextField plzField;
    private javax.swing.JTextField plzField1;
    private javax.swing.JTextField stadtField;
    private javax.swing.JTextField stadtField1;
    private javax.swing.JTextField strasseField;
    private javax.swing.JTextField strasseField1;
    private javax.swing.JTextField vornameField;
    private javax.swing.JTextField vornameField1;
    // End of variables declaration//GEN-END:variables

}
