/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PersonenAnsicht.java
 *
 * Created on 24.03.2009, 23:01:59
 */
package bibliotheksverwaltung.view;

import bibliotheksverwaltung.util.UpdateInfo;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

/**
 *
 * @author Max
 */
public class PersonenAnsicht extends ImagePanel implements Observer {

    /** Creates new form PersonenAnsicht */
    public PersonenAnsicht() {
        super("Person.png");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(182, 240));
        setPreferredSize(new java.awt.Dimension(182, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        JFrame jframe = new JFrame();
        jframe.setSize(200, 265);
        jframe.add(new PersonenAnsicht());
        jframe.setVisible(true);
    }

    /* (non-Javadoc)
     * @see java.util.Observer#update(java.util.Observable, java.lang.Object)
     */
    @Override
    public void update(Observable o, Object arg) {
        UpdateInfo updateInfo = (UpdateInfo) arg;
        this.removeAll();
        if (updateInfo.holeAenderung().equals("DatenBearbeiten")) {
            if (updateInfo.holeAenderungOk()) {
                //TODO was auch immer @Sven
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
