/*
 * ReportPanel.java
 *
 * Created on 25.03.2009, 16:14:50
 */

package bibliotheksverwaltung.view;

import bibliotheksverwaltung.model.daos.dao.MySQLStatistikDAO;
import bibliotheksverwaltung.model.domain.Statistik;

/**
 *
 * @author Max
 */
@SuppressWarnings("serial")
public class ReportPanel extends javax.swing.JPanel {

    /** Creates new form ReportPanel */
    public ReportPanel() {
        initComponents();
        fuelleFelder();
    }

    private void fuelleFelder() {
    	//TODO ist das zul�ssig? (mysqldao direkt aufzurufen)
    	Statistik statistik = new MySQLStatistikDAO().getStatistik();

    	buecherField.setText("" + statistik.getEingetrageneBuecher());
    	exemplareField.setText("" + statistik.getEingetragendeExemplare());
    	personenField.setText("" + statistik.getEingetragenePersonen());
    	leihenField.setText("" + statistik.getVerliehenBuecher());
    	ausleiherField.setText("" + statistik.getLeihendePersonen());
    	ausleihenGesamtField.setText("" + statistik.getBisherigeAusleihen());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statistikPanel = new javax.swing.JPanel();
        buecherLabel = new javax.swing.JLabel();
        buecherField = new javax.swing.JTextField();
        exemplareLabel = new javax.swing.JLabel();
        exemplareField = new javax.swing.JTextField();
        personenLabel = new javax.swing.JLabel();
        personenField = new javax.swing.JTextField();
        leihenLabel = new javax.swing.JLabel();
        leihenField = new javax.swing.JTextField();
        ausleiherLabel = new javax.swing.JLabel();
        ausleiherField = new javax.swing.JTextField();
        ausleihenGesamtLabel = new javax.swing.JLabel();
        ausleihenGesamtField = new javax.swing.JTextField();
        buchzustaendePanel = new javax.swing.JPanel();
        mahnButton = new javax.swing.JButton();
        statPrintButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(593, 600));

        statistikPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Statistik ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        buecherLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buecherLabel.setText("eingetragene Buecher");

        buecherField.setEditable(false);
        buecherField.setFont(new java.awt.Font("Arial", 1, 18));
        buecherField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        exemplareLabel.setFont(new java.awt.Font("Arial", 1, 14));
        exemplareLabel.setText("eingetragene Exemplare");

        exemplareField.setEditable(false);
        exemplareField.setFont(new java.awt.Font("Arial", 1, 18));
        exemplareField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        personenLabel.setFont(new java.awt.Font("Arial", 1, 14));
        personenLabel.setText("eingetragene Personen");

        personenField.setEditable(false);
        personenField.setFont(new java.awt.Font("Arial", 1, 18));
        personenField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        leihenLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        leihenLabel.setText("verliehene Buecher");

        leihenField.setEditable(false);
        leihenField.setFont(new java.awt.Font("Arial", 1, 18));
        leihenField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        ausleiherLabel.setFont(new java.awt.Font("Arial", 1, 14));
        ausleiherLabel.setText("leihende Personen");

        ausleiherField.setEditable(false);
        ausleiherField.setFont(new java.awt.Font("Arial", 1, 18));
        ausleiherField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        ausleihenGesamtLabel.setFont(new java.awt.Font("Arial", 1, 14));
        ausleihenGesamtLabel.setText("bisherige Ausleihen");

        ausleihenGesamtField.setEditable(false);
        ausleihenGesamtField.setFont(new java.awt.Font("Arial", 1, 18));
        ausleihenGesamtField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        buchzustaendePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buchzustaende", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        buchzustaendePanel.setMaximumSize(new java.awt.Dimension(186, 186));
        buchzustaendePanel.setMinimumSize(new java.awt.Dimension(186, 186));
        buchzustaendePanel.setOpaque(false);
        buchzustaendePanel.setPreferredSize(new java.awt.Dimension(186, 186));

        javax.swing.GroupLayout buchzustaendePanelLayout = new javax.swing.GroupLayout(buchzustaendePanel);
        buchzustaendePanel.setLayout(buchzustaendePanelLayout);
        buchzustaendePanelLayout.setHorizontalGroup(
            buchzustaendePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        buchzustaendePanelLayout.setVerticalGroup(
            buchzustaendePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statistikPanelLayout = new javax.swing.GroupLayout(statistikPanel);
        statistikPanel.setLayout(statistikPanelLayout);
        statistikPanelLayout.setHorizontalGroup(
            statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buecherLabel)
                    .addComponent(exemplareLabel)
                    .addComponent(ausleiherLabel)
                    .addComponent(leihenLabel)
                    .addComponent(ausleihenGesamtLabel)
                    .addComponent(personenLabel))
                .addGap(35, 35, 35)
                .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personenField)
                    .addComponent(exemplareField)
                    .addComponent(ausleiherField)
                    .addComponent(leihenField)
                    .addComponent(ausleihenGesamtField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buecherField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buchzustaendePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statistikPanelLayout.setVerticalGroup(
            statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistikPanelLayout.createSequentialGroup()
                .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statistikPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buecherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buecherField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exemplareLabel)
                            .addComponent(exemplareField))
                        .addGap(7, 7, 7)
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personenLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leihenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leihenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ausleiherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ausleiherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(statistikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ausleihenGesamtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ausleihenGesamtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addComponent(buchzustaendePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mahnButton.setFont(new java.awt.Font("Arial", 1, 18));
        mahnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/mail_write_48.png"))); // NOI18N
        mahnButton.setText("Mahnbriefe erstellen");
        mahnButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        statPrintButton.setFont(new java.awt.Font("Arial", 1, 18));
        statPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/paper_content_chart_48.png"))); // NOI18N
        statPrintButton.setText("Statistik drucken");
        statPrintButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statistikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mahnButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statPrintButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(statistikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mahnButton)
                    .addComponent(statPrintButton))
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ausleihenGesamtField;
    private javax.swing.JLabel ausleihenGesamtLabel;
    private javax.swing.JTextField ausleiherField;
    private javax.swing.JLabel ausleiherLabel;
    private javax.swing.JPanel buchzustaendePanel;
    private javax.swing.JTextField buecherField;
    private javax.swing.JLabel buecherLabel;
    private javax.swing.JTextField exemplareField;
    private javax.swing.JLabel exemplareLabel;
    private javax.swing.JTextField leihenField;
    private javax.swing.JLabel leihenLabel;
    private javax.swing.JButton mahnButton;
    private javax.swing.JTextField personenField;
    private javax.swing.JLabel personenLabel;
    private javax.swing.JButton statPrintButton;
    private javax.swing.JPanel statistikPanel;
    // End of variables declaration//GEN-END:variables

}
