/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WarenkorbEintragPanel.java
 *
 * Created on 24.03.2009, 20:48:00
 */

package bibliotheksverwaltung.view;

/**
 *
 * @author Max
 */
public class WarenkorbEintragPanel extends javax.swing.JPanel {

    /** Creates new form WarenkorbEintragPanel */
    public WarenkorbEintragPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exemplarLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        exemplarLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exemplarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/book_24.png"))); // NOI18N
        exemplarLabel.setText("ExemplarID");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheksverwaltung/view/images/cancel_24.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exemplarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton2)
                .addComponent(exemplarLabel))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exemplarLabel;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
